project:
  type: website

website:
  page-navigation: true
  title: "Harmony Nguyen"
  search: false
  favicon: "images/hn-favicon-color.png"
  
  navbar:
    logo: "images/logo-no-background.png"
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "CV/Resume"
        menu: 
          - text: "CV"
            href: cv.qmd
          - text: "Resume"
            href: resume.qmd
            
  
  page-footer: 
    right: "This page was built with ❤️ and [Quarto](https://quarto.org/)."
    
format:
  html:
    theme: 
      - cosmo
      - styles/cosmo.scss
    toc: false
    mainfont: "Atkinson Hyperlegible"
    include-in-header: "styles/fontawesome.html"    
    
editor: visual

freeze: auto



