project:
  type: website

website:
  page-navigation: true
  title: "Harmony Nguyen"
  search: true
  favicon: "images/hn-favicon-color.png"
  
  navbar:
    logo: "images/logo-no-background.png"
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "CV/Resume"
        href: cv_resume.qmd
  
format:
  html:
    theme: 
      - cosmo
      - styles/cosmo.scss
    toc: false
    mainfont: "Atkinson Hyperlegible"
    include-in-header: "styles/fontawesome.html"    
    
editor: visual

freeze: auto



